# -*- coding: utf-8 -*-
"""Image Caption Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OY_p6JRPMZkE74LEut6jRl82Htu9mXov"""


"""### Import required libraries"""

import gradio as gr
from transformers import BlipProcessor, BlipForConditionalGeneration
import torch
from PIL import Image

import warnings
warnings.filterwarnings("ignore")

"""### Load the model"""

processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-large")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-large")

"""### Define caption generating function"""

def generate_caption(image):
  raw_image = Image.open(image).convert("RGB")
  inputs = processor(raw_image, return_tensors = "pt")

  with torch.no_grad():
    out = model.generate(**inputs)

  caption = processor.decode(out[0], skip_special_tokens=True)
  return caption

"""### Interface using Gradio"""

interface = gr.Interface(
    fn = generate_caption,
    inputs = gr.Image(type="filepath"),
    outputs = gr.Textbox(label="Generated Caption"),
    title = "Image Caption Generator",
    description = "Upload an image and get an AI generated caption using BLIP model."
)

if __name__ == "__main__":
  interface.launch(share=True)

